/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_arreglado;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

/**
 *
 * @author giova
 */
public class Grafica extends javax.swing.JFrame {

    private Grafo miGrafo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParaGrafo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParaGrafo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelParaGrafo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    public Grafica(Grafo grafo) {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.miGrafo = grafo;
        this.setTitle("Analizador de Red Social (Grafos)");
        this.setPreferredSize(new Dimension(800, 600)); //
        this.pack();
        this.setLocationRelativeTo(null);
        dibujarGrafo();
    }

    private void dibujarGrafo() {

        if (miGrafo == null) {
            return;
        }

        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("RedSocial");
        String stylesheet = "graph {" + "fill-color:#222222;" + "}" + "node{" + "text-size: 25px;" + "text-color:white;" + "}";
        graph.setAttribute("ui.stylesheet", stylesheet);

        Vertice[] vertices = miGrafo.getVertices();
        for (Vertice v : vertices) {
            graph.addNode(v.usuario).setAttribute("ui.label", v.usuario);
        }

        int edgeId = 0;
        for (Vertice v : vertices) {
            String[] nombresAdyacentes = v.adyacentes.getNombres();
            for (String adyacente : nombresAdyacentes) {
                if (graph.getNode(adyacente) != null) {
                    graph.addEdge(String.valueOf(edgeId++), v.usuario, adyacente, true);
                }
            }
        }

        Vertice[][] componentes = miGrafo.encontrarComponentesFuertementeConectados();

        String[] colores = {"red", "blue", "green", "gold", "purple", "orange", "cyan", "pink"};
        int colorIndex = 0;
        for (Vertice[] componente : componentes) {
            String color = colores[colorIndex % colores.length];
            colorIndex++;
            for (Vertice v : componente) {
                if (graph.getNode(v.usuario) != null) {
                    graph.getNode(v.usuario).setAttribute("ui.style", "fill-color: " + color + ";");
                }
            }
        }

        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

        panelParaGrafo.setLayout(new BorderLayout());
        panelParaGrafo.add(viewPanel, BorderLayout.CENTER);
        panelParaGrafo.revalidate();
        panelParaGrafo.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelParaGrafo;
    // End of variables declaration//GEN-END:variables
}
