/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_arreglado;

import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    private Grafo nuevo = null;
    private Grafica ventanaGrafo = null;
    private Grafica VentanaActual;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botonCargar = new javax.swing.JButton();
        Resetear = new javax.swing.JButton();
        botonAgregarUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonAgregarRelacion = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        Usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Destino = new javax.swing.JTextField();
        Origen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonMostrarGrafo = new javax.swing.JButton();
        botonAnalizarCFC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CFC = new javax.swing.JTextArea();
        Exportar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCargar.setText("Cargar archivo de usuarios");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 20));

        Resetear.setText("Resetear grafo ");
        Resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetearActionPerformed(evt);
            }
        });
        getContentPane().add(Resetear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, -1));

        botonAgregarUsuario.setText("Agregar Usuario");
        botonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 50));

        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 50));

        botonAgregarRelacion.setText("Agregar Relación");
        botonAgregarRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRelacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 420, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 64, -1, -1));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 180, -1));

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoActionPerformed(evt);
            }
        });
        getContentPane().add(Destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        Origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrigenActionPerformed(evt);
            }
        });
        getContentPane().add(Origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, -1));

        jLabel3.setText("---> ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        botonMostrarGrafo.setText("Mostrar Grafo");
        botonMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, -1));

        botonAnalizarCFC.setText("Actualizar lista de usuarios / analizar CFC");
        botonAnalizarCFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarCFCActionPerformed(evt);
            }
        });
        getContentPane().add(botonAnalizarCFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 330, -1));

        CFC.setColumns(20);
        CFC.setRows(5);
        jScrollPane2.setViewportView(CFC);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 610, 130));

        Exportar.setText("Exportar txt");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });
        getContentPane().add(Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 210, 30));

        jLabel5.setText("Creador de Grafos / Usuarios seguidos ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel6.setText("@");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel7.setText("Agregar relacion / Conexiones enttre usuarios");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel8.setText("Usuario de Origen");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel9.setText("Usuario de Destino");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel10.setText("Creación del grafo ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel11.setText("Borrar grafo actual");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel12.setText("Identificar Usuarios con seguimientos en común o individuales");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jLabel2.setText("Exportación: Usuarios y relaciones entre ellos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        jLabel4.setText("@");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel13.setText("@");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
     nuevo = GestorArchivos.cargarGrafoDesdeArchivo();
     if (nuevo!= null) {
        JOptionPane.showMessageDialog(this, "Grafo cargado exitosamente. " + nuevo.getVertices().length + " usuarios encontrados.");
        CFC.setText("Grafo cargado. Listo para analizar.");
      }
    }//GEN-LAST:event_botonCargarActionPerformed

    private void botonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUsuarioActionPerformed
    String texto = "@"+ Usuario.getText().trim();
    if (texto.equals("@")) {
        JOptionPane.showMessageDialog(this, "El campo de usuario no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (nuevo == null) {
        nuevo = new Grafo(0);
    }
    boolean seInserto = nuevo.insertar(texto);
    if (seInserto) {
        JOptionPane.showMessageDialog(this, "Usuario '" + texto + "' agregado.");
    } else {
        JOptionPane.showMessageDialog(this, "El usuario '" + texto + "' ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    Usuario.setText("");
    }//GEN-LAST:event_botonAgregarUsuarioActionPerformed

    private void ResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetearActionPerformed
    this.nuevo = null;

    if (this.VentanaActual != null) {
        this.VentanaActual.dispose();
    }
    Usuario.setText("");
    CFC.setText("");
    JOptionPane.showMessageDialog(this, "El grafo ha sido reseteado y la memoria está limpia.");
    }//GEN-LAST:event_ResetearActionPerformed

    private void botonAgregarRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRelacionActionPerformed
    String origen = "@" + Origen.getText().trim();
    String destino = "@" + Destino.getText().trim();
    if (origen.isEmpty() || destino.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe llenar ambos campos (Origen y Destino).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (origen.equals(destino)) {
        JOptionPane.showMessageDialog(this, "Un usuario no puede seguirse a sí mismo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (nuevo == null) {
        JOptionPane.showMessageDialog(this, "Aún no se ha cargado ningún grafo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    boolean seAgrego = nuevo.agregarArista(origen, destino);
    if (seAgrego) {
        JOptionPane.showMessageDialog(this, "Relación '" + origen + " -> " + destino + "' agregada.");
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo agregar la relación. Verifique que:\n1. Los usuarios existan.\n2. La relación no sea un duplicado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    Origen.setText("");
    Destino.setText("");
    }//GEN-LAST:event_botonAgregarRelacionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinoActionPerformed

    private void OrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrigenActionPerformed

    private void botonMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarGrafoActionPerformed
        if (nuevo == null) {
            JOptionPane.showMessageDialog(this, "Aún no se ha cargado ningún grafo.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if (VentanaActual != null) {
            VentanaActual.dispose();
        }
        ventanaGrafo = new Grafica(nuevo);
        VentanaActual = ventanaGrafo;
        ventanaGrafo.setVisible(true);
    }//GEN-LAST:event_botonMostrarGrafoActionPerformed

    private void botonAnalizarCFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarCFCActionPerformed
    if (this.nuevo == null) {
        CFC.setText("Error: Aún no se ha cargado ningún grafo.");
        return;
    }
    String resultados = this.nuevo.getFuertementeconectados();
    CFC.setText(resultados);

    }//GEN-LAST:event_botonAnalizarCFCActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
      if (this.nuevo == null) {
         JOptionPane.showMessageDialog(this, "No hay nada que guardar.", "Error", JOptionPane.ERROR_MESSAGE);
         return;
        }
    GestorArchivos.guardarGrafoEnArchivo(this.nuevo);
    }//GEN-LAST:event_ExportarActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
    String texto = "@" + Usuario.getText().trim();
    if (texto.equals("@")) {
        JOptionPane.showMessageDialog(this, "El campo de usuario no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (nuevo == null) {
        JOptionPane.showMessageDialog(this, "El grafo está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    boolean seElimino = nuevo.eliminar(texto);
    if (seElimino) {
        JOptionPane.showMessageDialog(this, "Usuario '" + texto + "' eliminado.");
    } else {
        JOptionPane.showMessageDialog(this, "El usuario '" + texto + "' no existe.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    Usuario.setText("");
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CFC;
    private javax.swing.JTextField Destino;
    private javax.swing.JButton Exportar;
    private javax.swing.JTextField Origen;
    private javax.swing.JButton Resetear;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton botonAgregarRelacion;
    private javax.swing.JButton botonAgregarUsuario;
    private javax.swing.JButton botonAnalizarCFC;
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonMostrarGrafo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
